### ISSUE TITLE
Есть метод с массивом HttpMethods?

### ISSUE THREAD

**Issue by dmorgunov** [bohdan-shakhov/rick-and-morty-api#9]
https://github.com/bohdan-shakhov/rick-and-morty-api/blob/ac8487ea5dc21aafa0fda2e4c65e427c13d9c61a/src/main/java/com/example/rickandmorty/security/SecurityConfig.java#L38

**Comment by bohdan-shakhov** [comment]
я не нашёл, но выдал админу разрешению на запросы с любым http методом по адресу /api/admin/**
